name: Dispatch

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:

jobs:

  main:
    name: Main Process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.16
      GOLANGCI_LINT_VERSION: v1.41.1
      SEIHON_VERSION: v0.8.3
      CGO_ENABLED: 0

    steps:
      - name: Docker Login
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "PAT=$PAT"